#!/bin/bash
# Script to check file system usage and email per set threshould.
#
THRESHOULD=70
mailto="user@email.com"
HOSTNAME=$(hostname)
> /home/roger/bin/fscheck.out

for path in `/bin/df -h | grep -vE 'Filesystem|tmpfs' | awk '{print $5}' | sed 's/%//g'`
do
        if [ $path -ge $THRESHOULD ]; then
        df -h | grep $path% >> /home/roger/bin/fscheck.out
        fi
done

VALUE=`cat /home/roger/bin/fscheck.out | wc -l`
        if [ $VALUE -ge 1 ]; then
        mail -s "$HOSTNAME File System Usage Warning" $mailto < /home/roger/bin/fscheck.out
        fi
